// Regenerate only intentionally: existing puzzle numbers are part of saved progress.
import { writeFileSync } from 'node:fs';
import { BOOK_GRAPHS, LIGHTS_OUT_LEVELS, seededRandom } from '../assets/js/lib/lights-out-book-graphs.mjs';
import { pressEffect, solvePresses, countBits } from '../assets/js/lib/lights-out-math.mjs';

const catalogue = LIGHTS_OUT_LEVELS.map((level, difficulty) => {
  const random = seededRandom(0x10f00 + difficulty), puzzles = [], seen = new Set();
  const graphs = Object.values(BOOK_GRAPHS).filter(graph => level.sizes.includes(graph.size));
  const excluded = new Set();
  let cursor = 0;
  while (puzzles.length < 1000) {
    const target = level.presses[0] + Math.floor(puzzles.length * (level.presses[1] - level.presses[0] + 1) / 1000);
    const graph = graphs[cursor++ % graphs.length];
    if (excluded.has(`${graph.key}/${target}`)) continue;
    let found = false;
    for (let attempt = 0; attempt < 300; attempt++) {
      const choices = Array.from({ length: graph.size }, (_, i) => i);
      let presses = 0;
      for (let i = 0; i < target; i++) {
        const j = i + Math.floor(random() * (choices.length - i));
        [choices[i], choices[j]] = [choices[j], choices[i]];
        presses |= 1 << choices[i];
      }
      const lights = pressEffect(graph, presses), id = `${graph.key}/${lights}`;
      if (!lights || seen.has(id)) continue;
      const minimum = countBits(solvePresses(graph, lights).solutions[0]);
      if (minimum !== target) continue;
      puzzles.push([graph.key, lights, minimum]); seen.add(id); found = true; break;
    }
    if (!found) excluded.add(`${graph.key}/${target}`);
    if (graphs.every(candidate => excluded.has(`${candidate.key}/${target}`))) throw new Error(`Not enough distinct ${level.name} puzzles at ${target} presses.`);
  }
  console.log(`${level.name}: ${puzzles.length} distinct puzzles, ${new Set(puzzles.map(puzzle => puzzle[0])).size} graphs, ${level.presses.join('–')} presses.`);
  return puzzles;
});
writeFileSync(new URL('../assets/js/lib/lights-out-catalogue.mjs', import.meta.url), `// Generated by scripts/lights_out_catalogue.mjs. Preserve these puzzle numbers.\nexport const LIGHTS_OUT_CATALOGUE = ${JSON.stringify(catalogue)};\n`);
