import { writeFile } from 'node:fs/promises';
import { DIFFICULTIES, createArrangement, arrangementFingerprint } from '../assets/js/lib/tiling-arrangements.mjs';
import { occupiedCells, key } from '../assets/js/lib/tiling.mjs';

// Run explicitly to build the published catalogue. Keep it fixed between releases:
// puzzle numbers are permanent identities, rather than counters for random seeds.
const total = 1000, catalogue = [];
for (let difficulty = 0; difficulty < DIFFICULTIES.length; difficulty++) {
  const rows = [], seen = new Set();
  for (let seed = 1; rows.length < total; seed++) {
    const level = createArrangement(difficulty, seed), fingerprint = arrangementFingerprint(level);
    if (seen.has(fingerprint)) continue;
    seen.add(fingerprint);
    const cells = occupiedCells(level, level.solution);
    rows.push(Array.from({ length: level.height }, (_, y) => Array.from({ length: level.width }, (_, x) => cells.get(key(x, y)) || '.').join('')).join('/'));
  }
  catalogue.push(rows);
  console.log(`${DIFFICULTIES[difficulty].name}: ${rows.length} distinct solvable puzzles`);
}
await writeFile(new URL('../assets/js/lib/tiling-catalogue.mjs', import.meta.url),
  '// Generated by scripts/tiling_catalogue.mjs. Preserve these puzzle numbers.\n'
  + `export const CATALOGUE = Object.freeze(${JSON.stringify(catalogue, null, 2)}.map(Object.freeze));\n`);
